"""Initial schema with all models

Revision ID: 0ae54fa82ef0
Revises: 
Create Date: 2025-12-01 09:37:33.599976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0ae54fa82ef0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_collections_id'), 'search_collections', ['id'], unique=False)
    op.create_index(op.f('ix_search_collections_name'), 'search_collections', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('passkey_credential_id', sa.String(), nullable=True),
    sa.Column('passkey_public_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('search_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('document', sa.Text(), nullable=False),
    sa.Column('document_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['search_collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_documents_id'), 'search_documents', ['id'], unique=False)
    op.create_table('streams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('goblin', sa.String(), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streams_id'), 'streams', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('goblin', sa.String(), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_table('stream_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('cost_delta', sa.Float(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_chunks_id'), 'stream_chunks', ['id'], unique=False)
    op.drop_index(op.f('ix_provider_policies_timestamp'), table_name='provider_policies')
    op.drop_column('provider_policies', 'error_rate')
    op.drop_column('provider_policies', 'metadata_json')
    op.drop_column('provider_policies', 'timestamp')
    op.drop_column('provider_policies', 'response_time_ms')
    op.drop_column('provider_policies', 'is_healthy')
    op.drop_column('provider_policies', 'tokens_used')
    op.drop_column('provider_policies', 'throughput_rpm')
    op.drop_column('provider_policies', 'cost_incurred')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_policies', sa.Column('cost_incurred', sa.FLOAT(), nullable=True))
    op.add_column('provider_policies', sa.Column('throughput_rpm', sa.FLOAT(), nullable=True))
    op.add_column('provider_policies', sa.Column('tokens_used', sa.INTEGER(), nullable=True))
    op.add_column('provider_policies', sa.Column('is_healthy', sa.BOOLEAN(), nullable=False))
    op.add_column('provider_policies', sa.Column('response_time_ms', sa.FLOAT(), nullable=True))
    op.add_column('provider_policies', sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('provider_policies', sa.Column('metadata_json', sqlite.JSON(), nullable=True))
    op.add_column('provider_policies', sa.Column('error_rate', sa.FLOAT(), nullable=True))
    op.create_index(op.f('ix_provider_policies_timestamp'), 'provider_policies', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_stream_chunks_id'), table_name='stream_chunks')
    op.drop_table('stream_chunks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_streams_id'), table_name='streams')
    op.drop_table('streams')
    op.drop_index(op.f('ix_search_documents_id'), table_name='search_documents')
    op.drop_table('search_documents')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_search_collections_name'), table_name='search_collections')
    op.drop_index(op.f('ix_search_collections_id'), table_name='search_collections')
    op.drop_table('search_collections')
    # ### end Alembic commands ###
